kind: Service
apiVersion: v1
metadata:
  name: "my-ftp-service"
spec:
  selector:
    app: "my-ftp"
  ports:
    - name: port1
      port: 21
      nodePort: 30080
    - name: port2
      port: 31100
      nodePort: 31100
    - name: port3
      port: 31101
      nodePort: 31101
  type: LoadBalancer
